[project]
name = "ec2208-game"
version = "0.1.0"
description = "EC2208 Game Project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.2.0",
    "pygame>=2.6.1",
    "pygame-gui>=0.6.14",
]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
]
